name: ml-workshop
channels:
- conda-forge
- defaults
dependencies:
- h5py=2.7.0=np113py27_1
- hdf5=1.8.18=vc9_0
- keras=2.0.6=py27_0
- libgpuarray=0.6.9=vc9_0
- mako=1.0.7=py27_0
- pygpu=0.6.9=np113py27_0
- pyyaml=3.12=py27_1
- vc=9=0
- yaml=0.1.6=vc9_0
- backports=1.0=py27_0
- backports_abc=0.5=py27_0
- bleach=1.5.0=py27_0
- colorama=0.3.9=py27_0
- configparser=3.5.0=py27_0
- cycler=0.10.0=py27_0
- decorator=4.1.2=py27_0
- entrypoints=0.2.3=py27_0
- enum34=1.1.6=py27_0
- functools32=3.2.3.2=py27_0
- get_terminal_size=1.0.0=py27_0
- html5lib=0.999=py27_0
- icu=57.1=vc9_0
- ipykernel=4.6.1=py27_0
- ipython=5.3.0=py27_0
- ipython_genutils=0.2.0=py27_0
- ipywidgets=6.0.0=py27_0
- jinja2=2.9.6=py27_0
- jpeg=9b=vc9_0
- jsonschema=2.6.0=py27_0
- jupyter=1.0.0=py27_3
- jupyter_client=5.1.0=py27_0
- jupyter_console=5.1.0=py27_0
- jupyter_core=4.3.0=py27_0
- libpng=1.6.27=vc9_0
- libpython=2.0=py27_0
- m2w64-binutils=2.25.1=5
- m2w64-bzip2=1.0.6=6
- m2w64-crt-git=5.0.0.4636.2595836=2
- m2w64-gcc=5.3.0=6
- m2w64-gcc-ada=5.3.0=6
- m2w64-gcc-fortran=5.3.0=6
- m2w64-gcc-libgfortran=5.3.0=6
- m2w64-gcc-libs=5.3.0=7
- m2w64-gcc-libs-core=5.3.0=7
- m2w64-gcc-objc=5.3.0=6
- m2w64-gmp=6.1.0=2
- m2w64-headers-git=5.0.0.4636.c0ad18a=2
- m2w64-isl=0.16.1=2
- m2w64-libiconv=1.14=6
- m2w64-libmangle-git=5.0.0.4509.2e5a9a2=2
- m2w64-libwinpthread-git=5.0.0.4634.697f757=2
- m2w64-make=4.1.2351.a80a8b8=2
- m2w64-mpc=1.0.3=3
- m2w64-mpfr=3.1.4=4
- m2w64-pkg-config=0.29.1=2
- m2w64-toolchain=5.3.0=7
- m2w64-tools-git=5.0.0.4592.90b8472=2
- m2w64-windows-default-manifest=6.4=3
- m2w64-winpthreads-git=5.0.0.4634.697f757=2
- m2w64-zlib=1.2.8=10
- markupsafe=1.0=py27_0
- matplotlib=2.0.2=np113py27_0
- mistune=0.7.4=py27_0
- mkl=2017.0.3=0
- mkl-service=1.1.2=py27_3
- msys2-conda-epoch=20160418=1
- nbconvert=5.2.1=py27_0
- nbformat=4.3.0=py27_0
- notebook=5.0.0=py27_0
- numpy=1.13.1=py27_0
- openssl=1.0.2l=vc9_0
- pandas=0.20.3=py27_0
- pandocfilters=1.4.1=py27_0
- path.py=10.3.1=py27_0
- pathlib2=2.3.0=py27_0
- pickleshare=0.7.4=py27_0
- pip=9.0.1=py27_1
- prompt_toolkit=1.0.15=py27_0
- pygments=2.2.0=py27_0
- pyparsing=2.2.0=py27_0
- pyqt=5.6.0=py27_2
- python=2.7.13=1
- python-dateutil=2.6.1=py27_0
- pytz=2017.2=py27_0
- pyzmq=16.0.2=py27_0
- qt=5.6.2=vc9_6
- qtconsole=4.3.1=py27_0
- scandir=1.5=py27_0
- scipy=0.19.1=np113py27_0
- setuptools=27.2.0=py27_1
- simplegeneric=0.8.1=py27_1
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- ssl_match_hostname=3.5.0.1=py27_0
- subprocess32=3.2.7=py27_0
- testpath=0.3.1=py27_0
- theano=0.9.0=py27_0
- tk=8.5.18=vc9_0
- tornado=4.5.1=py27_0
- traitlets=4.3.2=py27_0
- vs2008_runtime=9.00.30729.5054=0
- wcwidth=0.1.7=py27_0
- wheel=0.29.0=py27_0
- widgetsnbextension=2.0.0=py27_0
- win_unicode_console=0.5=py27_0
- zlib=1.2.11=vc9_0
- pip:
  - backports-abc==0.5
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.15
  - win-unicode-console==0.5
prefix: C:\Users\Izy\Anaconda2\envs\ml-workshop

